use java_blog;

CREATE TABLE user (
  id int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
